// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: activationCode.sql

package db

import (
	"context"
	"database/sql"
)

const saveActivationCode = `-- name: SaveActivationCode :one
INSERT INTO activation_code (
    cadastro_id,
    activation_code,
    code,
    expires_at,
    status
)
VALUES ($1, $2, $3, $4, $5)
RETURNING cadastro_id, activation_code, code
`

type SaveActivationCodeParams struct {
	CadastroID     int64
	ActivationCode string
	Code           sql.NullString
	ExpiresAt      sql.NullTime
	Status         sql.NullString
}

type SaveActivationCodeRow struct {
	CadastroID     int64
	ActivationCode string
	Code           sql.NullString
}

func (q *Queries) SaveActivationCode(ctx context.Context, arg SaveActivationCodeParams) (SaveActivationCodeRow, error) {
	row := q.db.QueryRowContext(ctx, saveActivationCode,
		arg.CadastroID,
		arg.ActivationCode,
		arg.Code,
		arg.ExpiresAt,
		arg.Status,
	)
	var i SaveActivationCodeRow
	err := row.Scan(&i.CadastroID, &i.ActivationCode, &i.Code)
	return i, err
}
