// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type ActivationCode struct {
	CadastroID     int64
	ActivationCode string
	Status         sql.NullString
	Code           sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	ExpiresAt      sql.NullTime
}

type Admin struct {
	ID        int64
	Cnpj      string
	Name      string
	Email     string
	Password  string
	CreatedAt sql.NullTime
}

type Cadastro struct {
	ID             int64
	Name           string
	Cpf            sql.NullString
	Cnpj           sql.NullString
	Email          string
	Celular        string
	Password       string
	Status         string
	ActivationCode sql.NullString
	CreatedAt      sql.NullTime
}

type Produto struct {
	IDRoupa     int64
	Categoria   string
	Tamanho     string
	Cores       sql.NullString
	TempoValor  sql.NullFloat64
	Status      sql.NullString
	Localizacao sql.NullString
	ImagemUrl   sql.NullString
}

type Sale struct {
	ID         int64
	ProdutoID  sql.NullInt64
	Quantidade sql.NullInt32
	TempoValor sql.NullFloat64
	Total      sql.NullFloat64
	DataVenda  sql.NullTime
}

type Token struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt time.Time
	Active    bool
	CreatedAt time.Time
	AccessID  int64
}
