// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sale.sql

package db

import (
	"context"
	"database/sql"
)

const createSale = `-- name: CreateSale :one
INSERT INTO sales (produto_id, quantidade, tempo_valor)
VALUES ($1, $2, $3)
RETURNING id, produto_id, quantidade, tempo_valor, total, data_venda
`

type CreateSaleParams struct {
	ProdutoID  sql.NullInt64
	Quantidade sql.NullInt32
	TempoValor sql.NullFloat64
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRowContext(ctx, createSale, arg.ProdutoID, arg.Quantidade, arg.TempoValor)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.ProdutoID,
		&i.Quantidade,
		&i.TempoValor,
		&i.Total,
		&i.DataVenda,
	)
	return i, err
}
